### ISSUE TITLE
ZOS Grid 3.0

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#1165]
This is for tfgrid-3.0 
A draft and a general view of the operation on the tfgrid-3.0 will be is described in this WIP [document here](https://docs.google.com/document/d/152bjX_HmFJpwZCBtF-mxmDO8kZURsXO9IPxN5UeqolQ/edit?usp=sharing) 

So far this is the list of changes that need to be implmeneted
- [x] Yggdrasil support in containers [#1168]
- [x] New provision engine API that accepts connections and work loads from users/agents [#1169]
  - [x] Requests must be verified against identities on the grid-db
  - [x] Once reservation is accepted an HTTP 202 Accepted is returned
  - [x] User can then pull for status update of deployment (directly to the node)
- [x] Billing information is periodically send to the farmer agent (agent takes care of issuing bills) [#1199]
- [ ] ~~Node accept decommission requests from farmer agent (in case of no payments) it send back information about used capacity~~
- [x] On decommission on user request, information about unbilled consumed capacity is sent to the farmer agent.
- [ ] ~~Reservation expiration as per deployment object~~
- [x] Deployment modification in runtime (add/remove workloads)
   - [x] Also support modifying workloads inside deployment
- [x] Signature validation (again)

Also needed urgently
- [x] Refactor network daemon?
