### ISSUE TITLE
Implement GPU support

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#1972]
Limitations:
 - We start by supporting only one (and only one) GPU for now, while keeping in mind that more GPU can be available in zos node in the future 

## Changes
- [x] Identify and list all attached GPUs
- [ ] On registration, a node need to update its set of features on the chain (depends on chain change https://github.com/threefoldtech/tfchain/issues/720)
- [x] ZMachine can have an extra `gpu` flag (list of GPUs) 
   - [x] This is only accepted if node is dedicated (otherwise an error)
   - [X] A GPU can be only used by one ZMachine
- [X] Expose the gpu device to the VM (based on research here https://github.com/threefoldtech/zos/issues/1293#issuecomment-1070693016)

**Comment by muhamadazmy** [comment]
## Sub-tasks

> will be updated regularly

- [x] Identify GPU devices (scan the system PCI and filter via class, then figure out the vendor/device names
