### ISSUE TITLE
zinit: PID 1 for ZOS v2

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#34]
## Project 
https://github.com/threefoldtech/zinit

## Tasks
- [x] process manager in rust/toki POC
- [x] resolve dependencies of the services 
- [x] load services config from a directory
- [x] simple unix socket api to management 
- [x] command line tool to manage the process manager (status, stop, start, restart, and reload)
- [x] zombie reaping :fearful:
