### ISSUE TITLE
Design/Implement Virtual machine module [fcvm]

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#6]
## Technology:
Firecracker has been chosen to run the VM.

## To investigate:
- [x] check if k3os runs fine on firecracker: https://github.com/rancher/k3os/releases/tag/v0.8.0
- [x] test if firecracker VM can use a tap interface connected to a network resource bridge
- [x] test that raw file works properly as a way to give access to disks from the VM

## Module Design.
This module will be quite similar to the container module. Both needs to expose method to start/stop/inspect a VM/Container

There is an SDK for the firecracker API: https://github.com/firecracker-microvm/firecracker-go-sdk

## Todo

- [x] ~create udhcpd config -> in a separate NS is easier for networkd~ we found a way to assign an IP statically to the VM
- [x] create subvolume in a disk (where) to host images
  - VMs have their caveats: RAW image files are large, but at the same time we would need to have them fast. Storaged allow to create filesystem on top of multiple disk, so if big disks are required we could use thisf feature.
After some performance testing and if the speed is not good enough maybe we could investigate BCACHE.
 - [x] create flist for firecracker/K3OS images (or integrate firecracker in zos (0-initramfs)
```bash
ls -lh build/cargo_target/x86_64-unknown-linux-musl/release/{firecracker,jailer}
-rwxr-xr-x 2 delandtj delandtj 2.7M Jan 14 10:05 build/cargo_target/x86_64-unknown-linux-musl/release/firecracker
-rwxr-xr-x 2 delandtj delandtj 2.4M Jan 14 09:58 build/cargo_target/x86_64-unknown-linux-musl/release/jailer
```
- [x] create tap device and attach to NR -> needs schema definition ?
There is no schema definition for VMs, I think that will be necessary 
- [x] manage reservation size for volumes is not really specified, we wouldn't want quota break things

- [x] create an automated install procedure for k3os : 
  - prepare tap, attach to NR, bring up, disable_ipv6 (networkd)
  - prepare volume `fallocate, truncate` (storaged)
  - use api to configure vm fc instance (vmd)
    - mac addr
    - volume name / place
    - k3os.mode=install (and others)
  - boot autoinstall , wait ? kill ? (k3os automated install by default halts, instead of reboot :-/ ) (provisiond)
  - start it (provisiond)

**Comment by LeeSmet** [comment]
k3os installing is a pain, and uses initrd, which is not supported by firecracker. Trying to get the initrd as a cpio image in the kernel but that's apparently a different kind of worms. There are ways around this however in case we can't figure this out (though those do cost some effort as well). Tap interfaces seem to work fine. 2 k3s nodes running both on a firecracker, which each had a tap interface connected to the same bridge could be set up in a master/worker scenario, could reach each other over their flannel ifaces,... @delandtj also tested vxlans on zos itself and this all seems to work properly as is. Firecracker seems to not support qemu files, though we can use any arbitrary plain file as a disk (E.G `fallocate disk.img -l 50G` would create a file usable as a 50G disk).

Implementation wise, the VM module imo can be quite simple, as I'd prefer to keep the k3s specific code in the provision module. I estimate that a week should suffice for the VM (and some things for storage to get subvolumes I guess). Then we just have to fine tune the k3s install.

FYI as it currently stands we will also need to run dnsmasq in the vicinity  of the network resource

**Comment by delandtj** [comment]
@zaibon edit: moved this comment todo list in the first comment so we can track progress more easily.

**Comment by zaibon** [comment]
>  needs schema definition ?

see cause @muhamadazmy already started on that: https://github.com/threefoldtech/zos/blob/fcvm/pkg/vm.go

**Comment by LeeSmet** [comment]
For an automated intall, we can use a setup which matches this json:

```json
{
  "boot-source": {
    "kernel_image_path": "k3os-vmlinux",
    "initrd_path": "k3os-initrd-amd64",
    "boot_args": "console=ttyS0 reboot=k panic=1 k3os.mode=install k3os.install.silent k3os.install.device=/dev/vda k3os.token=clustertoken k3os.server_url=https://172.31.1.50:6443 ssh_authorized_keys=github:LeeSmet ssh_authorized_keys=github:delandtj ssh_authorized_keys=github:zaibon ssh_authorized_key=github:zgorizzo69"
  },
  "drives": [
    {
      "drive_id": "rootfs",
      "path_on_host": "ksos.img",
      "is_root_device": false,
      "is_read_only": false
    },
    {
      "drive_id": "install_media",
      "path_on_host": "k3os-amd64.iso",
      "is_root_device": false,
      "is_read_only": false 
      }
  ],
  "network-interfaces": [
    {
       "iface_id": "eth0",
       "host_dev_name": "tap0",
       "guest_mac": "AA:FC:00:00:00:03"
    }
  ],
  "machine-config": {
    "vcpu_count": 2,
    "mem_size_mib": 4096,
    "ht_enabled": false
  }
}
```

`k3os-initrd-amd64`, `k30s-amd64.iso` are files provided as is by the k3os repo. This repo also provides a kernel, though it is a compressed kernel which firecracker can't handle. We can however extract the uncompressed kernel via a shell script available in the linux kernel repo, to produce a `k3os-vmlinux` which can be booted. Alternatively we can also build our own kernel, which would allow us to add additional modules to the deployment. 

For the command line: 

- `console=ttyS0`: if we want output, so this might not be needed
- `reboot=k, panic=1`: default firecracker kernel params for proper functioning, this allows sending a shutdown command to the vm by issuing a `ctrl+alt+del` command.
- `k3os.install`: Start the installation on vm boot
- `k3os.install.silent`: Makes sure the install is unattended, i.e. no questions about configuration are asked at runtime. Anything that is configured is done through this command line
- `k3os.install.device`: Device on which to install, in this conifguration this is `/dev/vda`.
- `k3os.token`: cluster token, must be the same across all machines.
- `k3os.server_url`: IP of the master. Must only be set on worker nodes. The k3s port is 6443
- `ssh_authorized_keys`: SSH keys to be configured. Needs to be repeated for every ssh key. Either the full ssh key can be used, or the format `github:${Username}`, which will pull keys from github at boot

For the disks we have 2 entries: the "main" disk (a `fallocate`d file), and the ISO from which the install will run. Since we use an initrd, none of these disks can be marked as root_device.

The network iface does not seem to be strictly required at this stage, but it is needed later on anyway. Amount of cpu and memory is configurable as desired.

Right now, the default iso triggers a shutdown, which halts the vm but does not exit the process (as the vm does not emulate ACPI). For now we can do a time.Sleep(time.Minute) and then kill the process ourselves. (install time on my laptop is usually around 8-10 seconds, so this should suffice).

After this the vm can be booted again using the following config:

```json
{
  "boot-source": {
    "kernel_image_path": "k3os-vmlinux",
    "initrd_path": "/var/fcvms/k3os-initrd-amd64",
    "boot_args": "console=ttyS0 reboot=k panic=1"
  },
  "drives": [
    {
      "drive_id": "rootfs",
      "path_on_host": "/var/fcvms/ksos.img",
      "is_root_device": false,
      "is_read_only": false
    }
  ],
  "network-interfaces": [
    {
        "iface_id": "eth0",
        "host_dev_name": "tap0",
        "guest_mac": "AA:FC:00:00:00:03"
    }
  ],
  "machine-config": {
    "vcpu_count": 2,
    "mem_size_mib": 4096,
    "ht_enabled": false
  }
}
```

This time, the network is mandatory. The iso has also been removed. Only default firecracker kernel params are set in the boot_args this time around. Initrd is also not strictly required anymore, if it is removed, the `is_root_device` field on the disk should be set to true.

To provide an IP to the vm, the `guest_mac` should be set on the network device, to a known value, so we can run udhcpd in the network namespace. The following configuration seems to work for that:

```
start 172.31.1.50
end 172.31.1.100
interface n-6o1whsJC5JyBV 
option subnet 255.255.255.0
option router 172.31.1.1
option dns 8.8.8.8 8.8.4.4
static_lease AA:FC:00:00:00:03 172.31.1.50
```

`start` and `end` must obvisouly be in the NR subnet. `interface` is the name of the NR bridge inside the NR. `static_lease` is the chosen mac address, which is set on the VM network iface, followed by the IP it should have.

The network device (`iface_id`) is the name of the interface on the host. Firecracker only allows `tap` interfaces. The tap should be set to have the NR bridge in the default ns as master, ipv6 disabled on this interface, and brought up.

After this, we need to look how to set up ingress. From a vm perspective, we can add a secondary tap device, which will have public access. This needs to be further defined.

**Comment by zaibon** [comment]
https://github.com/threefoldtech/zos/pull/487
