### ISSUE TITLE
Network implementation

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#64]
Exit node:
- [x] [Define how the node gets its public IP configured](https://github.com/threefoldtech/zosv2/issues/60)

Network module:
- [x] [Logic to apply network resources](https://github.com/threefoldtech/zosv2/issues/61)
- [x] [Logic to request a new network resource for a node joining a network](https://github.com/threefoldtech/zosv2/issues/new)

FPA (farmer prefix allocator):
- [x] [Implement prefix allocator](https://github.com/threefoldtech/zosv2/issues/62)
- [x] [Define network object of farmer prefix allocator](https://github.com/threefoldtech/zosv2/issues/63)

**Comment by zaibon** [comment]
Most basic functionality have been merged to master.
- https://github.com/threefoldtech/zosv2/pull/74
- https://github.com/threefoldtech/zosv2/pull/86
- https://github.com/threefoldtech/zosv2/pull/96
